[package]
name    = "kore-tpch"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kore-tpch"
path = "src/main.rs"

[dependencies]
kore-core    = { workspace = true }
kore-sql     = { path = "../kore-sql" }
kore-join    = { path = "../kore-join" }
kore-window  = { path = "../kore-window" }
kore-shuffle = { path = "../kore-shuffle" }
kore-simd    = { path = "../kore-simd" }
kore-parallel = { path = "../kore-parallel" }
serde        = { workspace = true }
serde_json   = { workspace = true }
rayon        = { workspace = true }
