[package]
name    = "kore-bench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kore-bench"
path = "src/main.rs"

[[bin]]
name = "kore-stress"
path = "src/stress.rs"

[dependencies]
kore-core     = { workspace = true }
kore-join     = { workspace = true }
kore-cache    = { workspace = true }
kore-ml2      = { workspace = true }
kore-pipeline = { workspace = true }
kore-cluster  = { workspace = true }
kore-sql      = { workspace = true }
kore-store    = { workspace = true }
kore-ml3      = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
tokio         = { workspace = true }
