[package]
name    = "kore-net"
version = "0.1.0"
edition = "2021"

[features]
default = []
tls = ["dep:tokio-rustls", "dep:rustls-pemfile"]

[dependencies]
rmp-serde    = "1"
lz4_flex     = { workspace = true }
tokio-rustls = { version = "0.26", optional = true }
rustls-pemfile = { version = "2", optional = true }
kore-core  = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
tokio      = { workspace = true }

[dev-dependencies]
rcgen = "0.13"
