[package]
name = "kore-demo"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "kore-demo"
path = "src/main.rs"

[dependencies]
kore-core    = { path = "../kore-core" }
kore-sql     = { path = "../kore-sql" }
kore-parquet = { path = "../kore-parquet" }
kore-coord   = { path = "../kore-coord" }
kore-worker  = { path = "../kore-worker" }
kore-net     = { path = "../kore-net" }
tokio        = { workspace = true }

