[package]
name    = "kore-sql"
version = "0.1.0"
edition = "2021"

[dependencies]
kore-core   = { workspace = true }
kore-join   = { workspace = true }
kore-window = { workspace = true }
kore-spill  = { path = "../kore-spill" }
kore-store  = { path = "../kore-store" }
kore-delta  = { path = "../kore-delta" }
rayon       = { workspace = true }
thiserror   = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
