[package]
name    = "kore-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name  = "kore_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
kore-core    = { workspace = true }
kore-join    = { workspace = true }
kore-ml2     = { workspace = true }
kore-ml3     = { workspace = true }
kore-sql     = { workspace = true }
kore-io      = { workspace = true }
kore-parquet = { workspace = true }
kore-store   = { path = "../kore-store" }
serde_json   = { workspace = true }
thiserror    = { workspace = true }
libc         = { workspace = true }
