[package]
name = "kore-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
name = "kore_engine"
crate-type = ["cdylib"]

[dependencies]
kore-core    = { path = "../kore-core" }
kore-sql     = { path = "../kore-sql" }
kore-parquet = { path = "../kore-parquet" }
kore-io      = { path = "../kore-io" }
pyo3         = { version = "0.23", features = ["extension-module"] }
