// kore-self — Auto-generated: Lifecycle Engine — analyzes 'lifecycle' patterns in your memory
// Generated by kore-self Phase 6 (Self-Evolution)
// Edit and expand as needed. Wire into main.rs using self_evolve patch output.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use crate::Memory;

// ─── LifecycleEngine ─────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LifecycleEnginePattern {
    pub topic:      String,
    pub count:      u32,
    pub weight:     f64,
    pub last_seen:  String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LifecycleEngine {
    pub patterns:       Vec<LifecycleEnginePattern>,
    pub total_analyzed: u64,
    pub last_run:       String,
}

impl LifecycleEngine {
    pub fn new() -> Self {
        Self {
            patterns:       vec![],
            total_analyzed: 0,
            last_run:       "never".to_string(),
        }
    }

    /// Analyze all memories for 'lifecycle'-related patterns.
    pub fn analyze(&mut self, memories: &[Memory]) -> Vec<String> {
        if memories.is_empty() { return vec![]; }

        let keywords = expand_keywords("lifecycle");
        let mut freq: HashMap<String, (u32, f64)> = HashMap::new();

        for (i, m) in memories.iter().enumerate() {
            let content_lc = m.content.to_lowercase();
            if let Some(matched) = keywords.iter().find(|k| content_lc.contains(*k)) {
                let key = extract_phrase_around(&m.content, matched, 2);
                let recency = recency_weight(i, memories.len());
                let w = m.importance * (1.0 + recency);
                let e = freq.entry(key).or_insert((0, 0.0));
                e.0 += 1;
                e.1 += w;
            }
        }

        self.patterns.clear();
        for (topic, (count, weight)) in &freq {
            self.patterns.push(LifecycleEnginePattern {
                topic:     topic.clone(),
                count:     *count,
                weight:    weight / *count as f64,
                last_seen: crate::now(),
            });
        }
        self.patterns.sort_by(|a, b| b.count.cmp(&a.count));
        self.patterns.truncate(50);

        self.total_analyzed += memories.len() as u64;
        self.last_run        = crate::now();

        // Return insights as memory content strings
        self.patterns.iter().take(3).map(|p| {
            format!("[LifecycleEngine] '{}' detected {} times (avg importance {:.2})", p.topic, p.count, p.weight)
        }).collect()
    }

    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "total_analyzed": self.total_analyzed,
            "last_run":       self.last_run,
            "patterns":       self.patterns.len(),
            "top_patterns":   self.patterns.iter().take(10).map(|p| serde_json::json!({
                "topic":  p.topic,
                "count":  p.count,
                "weight": format!("{:.2}", p.weight),
            })).collect::<Vec<_>>(),
        })
    }
}

impl Default for LifecycleEngine {
    fn default() -> Self { Self::new() }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

fn extract_phrase_around(content: &str, keyword: &str, radius: usize) -> String {
    let words: Vec<&str> = content.split_whitespace().collect();
    let kw = keyword.to_lowercase();
    for (i, w) in words.iter().enumerate() {
        let w_clean = w.trim_matches(|c: char| !c.is_alphanumeric()).to_lowercase();
        if w_clean == kw || w_clean.contains(&kw) {
            let start = i.saturating_sub(radius);
            let end = (i + radius + 1).min(words.len());
            return words[start..end]
                .iter()
                .map(|w| w.trim_matches(|c: char| !c.is_alphanumeric()).to_lowercase())
                .collect::<Vec<_>>()
                .join(" ");
        }
    }
    kw
}

fn extract_key(content: &str, keyword: &str) -> String {
    extract_phrase_around(content, keyword, 1)
}

fn expand_keywords(base: &str) -> Vec<String> {
    let mut out = vec![base.to_lowercase()];
    if !base.ends_with('s') {
        out.push(format!("{}s", base));
    }
    if base.ends_with('s') && base.len() > 1 {
        out.push(base[..base.len()-1].to_lowercase());
    }
    match base.to_lowercase().as_str() {
        "goal" | "goals" => { out.push("target".to_string()); out.push("objective".to_string()); }
        "feel" | "feels" | "mood" | "moods" | "emotion" | "emotions" | "stress" => {
            out.push("happy".to_string());
            out.push("sad".to_string());
            out.push("tired".to_string());
            out.push("angry".to_string());
        }
        "learn" | "learning" | "skill" | "skills" | "study" => {
            out.push("course".to_string());
            out.push("practice".to_string());
            out.push("read".to_string());
        }
        "time" | "schedule" | "deadline" | "routine" | "daily" | "week" => {
            out.push("plan".to_string());
            out.push("calendar".to_string());
            out.push("appointment".to_string());
        }
        "problem" | "error" | "bug" | "issue" | "debug" | "fail" => {
            out.push("fix".to_string());
            out.push("broken".to_string());
            out.push("crash".to_string());
        }
        _ => {}
    }
    out.sort();
    out.dedup();
    out
}

fn recency_weight(index: usize, total: usize) -> f64 {
    if total == 0 { return 1.0; }
    (index as f64 + 1.0) / total as f64
}
