import os, subprocess, time, hashlib, sys
from pathlib import Path

TOOLS_DIR = Path(__file__).parent
CSV = TOOLS_DIR / 'sample_10mb.csv'
KORE = TOOLS_DIR / 'sample_10mb.kore'
KORE_GZ = TOOLS_DIR / 'sample_10mb.kore.gz'
PARQUET = TOOLS_DIR / 'sample_10mb.parquet'

def sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            h.update(chunk)
    return h.hexdigest()

results = []

# CSV exists
if not CSV.exists():
    print('CSV not found; run generate_csv.py first')
    sys.exit(1)

# KORE conversion
start = time.time()
proc = subprocess.run([sys.executable, str(TOOLS_DIR / 'csv_to_kore.py'), str(CSV), str(KORE)], capture_output=True, text=True)
end = time.time()
results.append(('csv->kore', str(CSV), str(KORE), end-start, KORE.exists() and KORE.stat().st_size or 0, KORE.exists() and sha256(KORE) or ''))
if proc.returncode != 0:
    print(proc.stdout)
    print(proc.stderr)

# Gzip pack (if exists)
start = time.time()
proc = subprocess.run([sys.executable, str(TOOLS_DIR / 'pack_kore.py'), str(KORE)], capture_output=True, text=True)
end = time.time()
results.append(('kore->gz', str(KORE), str(KORE_GZ), end-start, KORE_GZ.exists() and KORE_GZ.stat().st_size or 0, KORE_GZ.exists() and sha256(KORE_GZ) or ''))
if proc.returncode != 0:
    print(proc.stdout); print(proc.stderr)

# Parquet conversion
try:
    start = time.time()
    proc = subprocess.run([sys.executable, str(TOOLS_DIR / 'csv_to_parquet.py'), str(CSV), str(PARQUET)], capture_output=True, text=True)
    end = time.time()
    if proc.returncode != 0:
        print('PARQUET conversion failed:')
        print(proc.stdout); print(proc.stderr)
        results.append(('csv->parquet', str(CSV), str(PARQUET), None, 0, 'FAILED'))
    else:
        results.append(('csv->parquet', str(CSV), str(PARQUET), end-start, PARQUET.exists() and PARQUET.stat().st_size or 0, PARQUET.exists() and sha256(PARQUET) or ''))
except Exception as e:
    results.append(('csv->parquet', str(CSV), str(PARQUET), None, 0, f'ERROR: {e}'))

# Also record CSV metadata
results.insert(0, ('csv', str(CSV), str(CSV), 0.0, CSV.stat().st_size, sha256(CSV)))

# Print table
print('\nConversion results:')
print('| Step | Source | Output | Duration(s) | Size(bytes) | sha256 |')
print('|---|---|---:|---:|---:|---|')
for r in results:
    dur = f"{r[3]:.3f}" if isinstance(r[3], float) else (r[3] if r[3] is not None else '')
    size = str(r[4]) if r[4] else ''
    print(f'| {r[0]} | {Path(r[1]).name} | {Path(r[2]).name} | {dur} | {size} | {r[5]} |')

# Save full output to a file
with open(TOOLS_DIR / 'conversion_report.md', 'w', encoding='utf-8') as f:
    f.write('# Conversion report\n\n')
    f.write('Generated by run_conversion.py\n\n')
    f.write('| Step | Source | Output | Duration(s) | Size(bytes) | sha256 |\n')
    f.write('|---|---|---:|---:|---:|---|\n')
    for r in results:
        dur = f"{r[3]:.3f}" if isinstance(r[3], float) else (r[3] if r[3] is not None else '')
        size = str(r[4]) if r[4] else ''
        f.write(f'| {r[0]} | {Path(r[1]).name} | {Path(r[2]).name} | {dur} | {size} | {r[5]} |\n')
print('\nReport written to', TOOLS_DIR / 'conversion_report.md')
