[package]
name    = "kore-worker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kore-worker"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
kore-core    = { workspace = true }
kore-net     = { path = "../kore-net" }
kore-sql     = { path = "../kore-sql" }
kore-shuffle = { path = "../kore-shuffle" }
serde_json   = { workspace = true }
tokio        = { workspace = true }
