name: Publish to crates.io

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Publish to crates.io
        run: cargo publish -p kore-ffi --token "${{ secrets.CARGO_REGISTRY_TOKEN }}" --allow-dirty


